// Customer-facing "Accept & Confirm" link on a quote email - the same
// self-serve pattern as design-proofs.js's approve/decline, just applied one
// step earlier in the pipeline (accepting the quote itself, not a design
// proof attached to it). No login: an unguessable accept_token (orders.
// accept_token, generated by send-email.js the first time a quote goes out)
// is the only credential. Decisions are POSTed here, never a plain GET link,
// for the same reason as proof.html - a link-prefetching scanner or email
// client can't accidentally "click" Accept on someone's behalf.
export async function onRequest(context) {
  const { request, env } = context;
  const db = env.DB;

  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Content-Type": "application/json",
    "Cache-Control": "no-store",
  };

  if (request.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const json = (body, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: corsHeaders });

  const escapeHtml = (str) => String(str ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const money = (n) => "£" + Number(n || 0).toFixed(2);

  try {
    // Guard against a cold deploy hitting this file before send-email.js or
    // orders.js has - same "already exists" tolerance as everywhere else.
    try {
      await db.prepare(`ALTER TABLE orders ADD COLUMN accept_token TEXT`).run();
    } catch {
      // already exists
    }

    const url = new URL(request.url);

    // GET ?token=X - public, unauthenticated lookup for accept-quote.html:
    // just enough to render the decision page, no other order/customer data
    // leaks through this one.
    if (request.method === "GET") {
      const token = url.searchParams.get("token");
      if (!token) return json({ error: "Missing token" }, 400);
      const o = await db.prepare(
        "SELECT id, quote_number, customer_name, total, status, deposit_pct, deposit_amount, doc_type FROM orders WHERE accept_token = ?"
      ).bind(token).first();
      if (!o) return json({ error: "This link isn't valid." }, 404);
      if (o.doc_type !== "quote") {
        return json({ error: "This quote has already moved on - check your email for the latest invoice." }, 409);
      }
      const depositDue = Math.min(o.total, o.total * (Number(o.deposit_pct || 0) / 100) + Number(o.deposit_amount || 0));
      return json({
        quote_number: o.quote_number, customer_name: o.customer_name, total: o.total,
        status: o.status, deposit_due: depositDue > 0 ? depositDue : 0,
      });
    }

    if (request.method !== "POST") {
      return json({ error: "Method not allowed" }, 405);
    }

    const data = await request.json();
    if (!data.token) return json({ error: "token is required" }, 400);
    if (data.decision !== "approved" && data.decision !== "declined") {
      return json({ error: "decision must be 'approved' or 'declined'" }, 400);
    }

    const o = await db.prepare("SELECT * FROM orders WHERE accept_token = ?").bind(data.token).first();
    if (!o) return json({ error: "This link isn't valid." }, 404);
    if (o.doc_type !== "quote") {
      return json({ error: "This quote has already moved on - check your email for the latest invoice." }, 409);
    }
    if (o.status === "approved" || o.status === "declined") {
      return json({ error: `This quote was already marked ${o.status} - no further action needed.` }, 409);
    }

    const notes = String(data.notes || "").slice(0, 1000);
    await db.prepare("UPDATE orders SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?")
      .bind(data.decision, o.id).run();

    // Approving converts straight to an invoice and emails it out - reusing
    // the exact same internal endpoints Martin would otherwise click by hand
    // (see design-proofs.js, which does the identical thing on proof
    // approval) so this can never drift from what a manual convert/send
    // actually does. The invoice's first-ever send is what actually asks
    // for the deposit (send-email.js's isFirstSend) - nothing extra needed
    // here to "fire off" that ask, it's just the natural first send of a
    // freshly-converted invoice. Wrapped so a failure here never undoes the
    // acceptance itself, which is already safely recorded.
    let invoiceNumber = null;
    let invoiced = false;
    let invoiceEmailed = false;
    if (data.decision === "approved") {
      try {
        const convertRes = await fetch(`${url.origin}/api/orders`, {
          method: "PUT", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: o.id, action: "convert_to_invoice" }),
        });
        const convertData = await convertRes.json();
        if (convertRes.ok && convertData.success) {
          invoiced = true;
          invoiceNumber = convertData.invoice_number;
          const emailRes = await fetch(`${url.origin}/api/send-email`, {
            method: "POST", headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ order_id: o.id }),
          });
          invoiceEmailed = emailRes.ok;
        }
      } catch (e) {
        // Acceptance is still recorded either way - Martin can convert/send
        // by hand from the portal if this automation failed.
      }
    }

    // Notify the portal - same pattern as design-proofs.js's decision
    // notification.
    if (env.RESEND_API_KEY) {
      const notifyTo = env.NOTIFY_EMAIL_TO || env.RESEND_REPLY_TO || "hello@embroidery.click";
      const fromAddress = env.RESEND_FROM_EMAIL || "Crystal Custom Embroidery <onboarding@resend.dev>";
      const verb = data.decision === "approved" ? "Accepted" : "Declined";
      const invoiceNote = invoiced
        ? `<p><strong>${escapeHtml(invoiceNumber)}</strong> was created automatically and ${invoiceEmailed ? "emailed to the customer" : "could not be emailed - send it from the portal"}.</p>`
        : "";
      try {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { "Authorization": `Bearer ${env.RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: fromAddress,
            to: [notifyTo],
            subject: `Quote ${verb}: ${o.quote_number} - ${o.customer_name}${invoiced ? " - now " + invoiceNumber : ""}`,
            html: `<p><strong>${escapeHtml(o.customer_name)}</strong> has <strong>${verb.toLowerCase()}</strong> quote ${escapeHtml(o.quote_number)} (${money(o.total)}).</p>` +
              (notes ? `<p><strong>Their note:</strong> ${escapeHtml(notes)}</p>` : "") + invoiceNote,
          }),
        });
      } catch (e) {
        // Notification failing shouldn't fail the customer's decision.
      }
    }

    return json({ success: true, status: data.decision, invoiced, invoice_number: invoiceNumber, invoice_emailed: invoiceEmailed });
  } catch (err) {
    return json({ error: err.message }, 500);
  }
}
