// Customer-facing "Accept & Confirm" link on a quote email - the same
// self-serve pattern as design-proofs.js's approve/decline, just applied one
// step earlier in the pipeline (accepting the quote itself, not a design
// proof attached to it). No login: an unguessable accept_token (orders.
// accept_token, generated by send-email.js the first time a quote goes out)
// is the only credential. Decisions are POSTed here, never a plain GET link,
// for the same reason as proof.html - a link-prefetching scanner or email
// client can't accidentally "click" Accept on someone's behalf.
export async function onRequest(context) {
  const { request, env } = context;
  const db = env.DB;

  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Content-Type": "application/json",
    "Cache-Control": "no-store",
  };

  if (request.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const json = (body, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: corsHeaders });

  const escapeHtml = (str) => String(str ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const money = (n) => "£" + Number(n || 0).toFixed(2);

  try {
    // Guard against a cold deploy hitting this file before send-email.js or
    // orders.js has - same "already exists" tolerance as everywhere else.
    for (const col of ["accept_token TEXT", "pay_token TEXT"]) {
      try {
        await db.prepare(`ALTER TABLE orders ADD COLUMN ${col}`).run();
      } catch {
        // already exists
      }
    }

    const url = new URL(request.url);

    // GET ?token=X - public, unauthenticated lookup for accept-quote.html:
    // just enough to render the decision page, no other order/customer data
    // leaks through this one.
    if (request.method === "GET") {
      const token = url.searchParams.get("token");
      if (!token) return json({ error: "Missing token" }, 400);
      const o = await db.prepare(
        "SELECT id, quote_number, invoice_number, customer_name, total, amount_paid, paid_status, status, deposit_pct, deposit_amount, doc_type, pay_token FROM orders WHERE accept_token = ?"
      ).bind(token).first();
      if (!o) return json({ error: "This link isn't valid." }, 404);
      // Not an error case - this is exactly what a successful acceptance
      // looks like once the quote has already become an invoice. Shown as
      // a normal confirmation on the page, not red error text (see
      // accept-quote.html's "converted" branch). Also where the "pay by
      // card" offer actually lives - the accept-quote page is the natural
      // moment to ask, right after they've just said yes, rather than only
      // via the separate invoice email that goes out a moment later.
      if (o.doc_type !== "quote") {
        const balance = Number(o.total) - Number(o.amount_paid || 0);
        const rawDepositDue = Math.min(o.total, o.total * (Number(o.deposit_pct || 0) / 100) + Number(o.deposit_amount || 0));
        // Only worth offering as its own smaller option if it's genuinely
        // smaller than paying in full outright - otherwise it's the same
        // choice twice. "No less than the deposit set on the quote" - this
        // is never reduced for any reason other than capping at what's
        // actually still owed (see pay-by-card.js's own mode=deposit
        // handling, which computes this identical figure independently
        // rather than trusting a client-supplied amount).
        const depositDue = (rawDepositDue > 0 && rawDepositDue < balance) ? Math.min(rawDepositDue, balance) : 0;
        return json({
          converted: true, quote_number: o.quote_number, customer_name: o.customer_name,
          invoice_number: o.invoice_number, total: o.total, balance, paid_status: o.paid_status,
          deposit_due: depositDue, pay_token: o.pay_token,
        });
      }
      const depositDue = Math.min(o.total, o.total * (Number(o.deposit_pct || 0) / 100) + Number(o.deposit_amount || 0));
      return json({
        quote_number: o.quote_number, customer_name: o.customer_name, total: o.total,
        status: o.status, deposit_due: depositDue > 0 ? depositDue : 0,
      });
    }

    if (request.method !== "POST") {
      return json({ error: "Method not allowed" }, 405);
    }

    const data = await request.json();
    if (!data.token) return json({ error: "token is required" }, 400);
    if (data.decision !== "approved" && data.decision !== "declined") {
      return json({ error: "decision must be 'approved' or 'declined'" }, 400);
    }

    const o = await db.prepare("SELECT * FROM orders WHERE accept_token = ?").bind(data.token).first();
    if (!o) return json({ error: "This link isn't valid." }, 404);
    // Safety net for a double-submit race (the page itself won't normally
    // offer the buttons once converted - see the GET branch above) - still
    // framed as a positive confirmation, not an error.
    if (o.doc_type !== "quote") {
      return json({ converted: true, quote_number: o.quote_number, customer_name: o.customer_name });
    }
    if (o.status === "approved" || o.status === "declined") {
      return json({ error: `This quote was already marked ${o.status} - no further action needed.` }, 409);
    }

    const notes = String(data.notes || "").slice(0, 1000);
    await db.prepare("UPDATE orders SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?")
      .bind(data.decision, o.id).run();

    // Approving converts straight to an invoice and emails it out - reusing
    // the exact same internal endpoints Martin would otherwise click by hand
    // (see design-proofs.js, which does the identical thing on proof
    // approval) so this can never drift from what a manual convert/send
    // actually does. The invoice's first-ever send is what actually asks
    // for the deposit (send-email.js's isFirstSend) - nothing extra needed
    // here to "fire off" that ask, it's just the natural first send of a
    // freshly-converted invoice. Wrapped so a failure here never undoes the
    // acceptance itself, which is already safely recorded.
    let invoiceNumber = null;
    let invoiced = false;
    let invoiceEmailed = false;
    if (data.decision === "approved") {
      try {
        // These internal calls hit /api/orders and /api/send-email exactly
        // like the admin portal itself would - and functions/_middleware.js
        // gates every /api/* route behind the portal login unless it's
        // carrying a valid session cookie (which a server-to-server fetch
        // has none of) or the X-API-Key header. auth_config.api_key is the
        // same key generated by the portal's "API Key" button and already
        // handed to the cron Worker as PORTAL_API_KEY - fetched straight
        // from D1 here rather than needing its own env var, since it's
        // already sitting in the same database. Without it these two calls
        // would 401 silently (caught below) - the acceptance itself would
        // still record, but nothing would ever actually convert or send.
        const authCfg = await db.prepare("SELECT api_key FROM auth_config WHERE id = 'default'").first();
        const authHeaders = { "Content-Type": "application/json" };
        if (authCfg && authCfg.api_key) authHeaders["X-API-Key"] = authCfg.api_key;

        const convertRes = await fetch(`${url.origin}/api/orders`, {
          method: "PUT", headers: authHeaders,
          body: JSON.stringify({ id: o.id, action: "convert_to_invoice" }),
        });
        const convertData = await convertRes.json();
        if (convertRes.ok && convertData.success) {
          invoiced = true;
          invoiceNumber = convertData.invoice_number;
          const emailRes = await fetch(`${url.origin}/api/send-email`, {
            method: "POST", headers: authHeaders,
            body: JSON.stringify({ order_id: o.id }),
          });
          invoiceEmailed = emailRes.ok;
        }
      } catch (e) {
        // Acceptance is still recorded either way - Martin can convert/send
        // by hand from the portal if this automation failed.
      }
    }

    // Notify the portal - same pattern as design-proofs.js's decision
    // notification.
    if (env.RESEND_API_KEY) {
      const notifyTo = env.NOTIFY_EMAIL_TO || env.RESEND_REPLY_TO || "hello@embroidery.click";
      const fromAddress = env.RESEND_FROM_EMAIL || "Crystal Custom Embroidery <onboarding@resend.dev>";
      const verb = data.decision === "approved" ? "Accepted" : "Declined";
      const invoiceNote = invoiced
        ? `<p><strong>${escapeHtml(invoiceNumber)}</strong> was created automatically and ${invoiceEmailed ? "emailed to the customer" : "could not be emailed - send it from the portal"}.</p>`
        : "";
      try {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { "Authorization": `Bearer ${env.RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: fromAddress,
            to: [notifyTo],
            subject: `Quote ${verb}: ${o.quote_number} - ${o.customer_name}${invoiced ? " - now " + invoiceNumber : ""}`,
            html: `<p><strong>${escapeHtml(o.customer_name)}</strong> has <strong>${verb.toLowerCase()}</strong> quote ${escapeHtml(o.quote_number)} (${money(o.total)}).</p>` +
              (notes ? `<p><strong>Their note:</strong> ${escapeHtml(notes)}</p>` : "") + invoiceNote,
          }),
        });
      } catch (e) {
        // Notification failing shouldn't fail the customer's decision.
      }
    }

    return json({ success: true, status: data.decision, invoiced, invoice_number: invoiceNumber, invoice_emailed: invoiceEmailed });
  } catch (err) {
    return json({ error: err.message }, 500);
  }
}
